apiVersion: v1
kind: Pod
metadata:
  name: bsos-demo
spec:
  containers:
    - name: busybox
      image: public.ecr.aws/docker/library/busybox:1.37
      command: ["sleep", "86400"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: bsos-pvc
